// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence.Context;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20241110095039_newmig")]
    partial class newmig
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Gym_Users_master", b =>
                {
                    b.Property<int>("GU_ID")
                        .HasColumnType("int");

                    b.Property<string>("GU_GM_ID")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("GU_MOBILE")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("GU_AADHAR")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("GU_CREATE_DATE")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("GU_DOB")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("GU_EMAIL")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("GU_FIRST_NAME")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("GU_GENDER")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("GU_LAST_NAME")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("GU_PAN")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("GU_PHOTO")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("GU_P_TYPE")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("GU_UPDATE_DATE")
                        .HasColumnType("datetime(6)");

                    b.HasKey("GU_ID", "GU_GM_ID", "GU_MOBILE");

                    b.ToTable("Gym_User_Master");
                });
#pragma warning restore 612, 618
        }
    }
}
